positive_keywords = [
    "Impf",
    "Booster",
    "Spritze",
    "Omikron",
    "Delta",
    "Patient",
    "Symptom",
    "Inzidenz",
    "Infektion",
    "infektionsverstärk",
    "Antikörper",
    "Enhancement",
    "Massen",
    "Genozid",
    "Völkermord",
    "Bevölkerungsreduktion",
    "DNA",
    "Genexperiment",
    "genetisch",
    "genveränder",
    "irreversibel",
    "Graphen",
    "Nano",
    "natürliche immuni",
    "wirksam",
    "unfruchtbar",
    "Menstruation",
    "Fehlgeburt",
    "Spike",
    "Protein",
    "toxisch",
    "Blutge",
    "Organ",
    "Nebenwirkung",
    "infektiös",
    "Risiko",
    "Immunsystem",
    "Myokarditis",
    "Thrombose",
    "schwächt",
    "Langzeitfolgen",
    "Krebs",
    "Gift",
    "Ausleit",
    "Cocktail",
    "Shedding",
    "Bhakdi",
    "Wodarg",
    "Malone",
    "McCullough",
]
negative_keywords = [
    # exclude messages about political measures
    "Politik",
    "Einzelhandel",
    "Clubs",
    "Diskothek",
    "Gastronomie",
    "Konzert",
    "Theater",
    # exclude lab origin theory
    "Laborursprung",
    "Labor-Ursprung",
    # exclude message daily Corona news
    "7-Tage-Inzidenz",
    "Gesundheitsämter",
    "RKI",
    "Söder",
    "Schweiz",
    "Österreich",
    "Australien",
    "Lauterbach",
    "Impfpflicht",
    "Ticker",
    "Bescheinigung",
    "Kimmich",
    "Bayer",
    # exclude messages about other news
    "Schneesturm",
    "Kasach",
    "Ukrain",
    "Donezk",
    "Luhansk",
    "Russland",
    "russisch",
    "Ottawa",
    "Trucker",
    "Freedom Convoy",
    "Putin",
    "Quebec",
    "Faeser",
    "Steinmeier",
    "Lindner",
    "Inflation",
    "Djokovic",
    # exclude messages about transhumanism, prepping, etc.
    "Lieferkette",
    "Augmentation",
    # exclude messages about climate change
    "Klima",
    # exclude messages about real or imagined discrimination of the unvaccinated
    "Stigmatisierung",
    "für Ungeimpfte",
    "schikan",
    "Fahrschul",
    "Bundeswehr",
    "öffentlich-rechtlich",
    # exclude announcements of events, demonstrations, etc.
    "Corona-Ausschuss",
    "Planspiel",
    "Spazier",
    "Demonstration",
    "Kundgebung",
    "Polizei",
    "Düsseldorf",
]
